name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: curl -L https://www.wordmashup.xyz/dashboard
